### ISSUE TITLE
About locA score

### ISSUE THREAD

**Issue by Spritea** [JonathonLuiten/HOTA-metrics#5] opened 2021-02-07 15:56 UTC
Hi Jonathon,

I tried use ground truth files as tracker prediction result to test the code. For most metrics, including HOTA, they are 100%, which is reasonable. But for locA score under HOTA_AUC section, it's over 99%, but not 100%.

The ground truth file I use is MOT17-04-DPM, and I remove all other classes, except pedestrain class as the tracker's prediction file. I use earlier version code before current version. Could you explain it, thanks!

**Comment by JonathonLuiten** [comment] 2021-02-07 17:31
Interesting. Could be something numerical caused by some kind of rounding somewhere maybe. I'm not sure.

I've added it to my list of things to look into.

Cheers,
Jono

**Comment by JonathonLuiten** [comment] 2021-02-09 16:40
So I just looked into this, and I cannot reproduce the error. I get perfect 100% always.

Maybe you just accidently edited some of the boxes while you were removing the non-person class?

Can you try with this tracker file? (Should be the same as yours, just the GT with the non-person removed)

[MOT17-04-DPM.txt](https://github.com/JonathonLuiten/HOTA-metrics/files/5952770/MOT17-04-DPM.txt)

**Comment by Spritea** [comment] 2021-02-09 16:51
Thanks for your reply!

But even when I use your txt file as the tracker prdiction result, I reproduce the error again.

Below is my screenshot, and note that I use an **earlier** version, **before** current December version code.

![image](https://user-images.githubusercontent.com/22995173/107397728-e0937480-6b39-11eb-9e88-d1d980401d79.png)

**Comment by JonathonLuiten** [comment] 2021-02-09 16:58
Could you try to run it with the most recent version? Maybe the fixes all of your issues and then sorted? Not sure.

**Comment by Spritea** [comment] 2021-02-09 17:03
OK, I'll try the latest version then. Thanks!

**Comment by JonathonLuiten** [comment] 2021-02-10 13:12
Did it work with the latest version? Depending on how old the version you were using was I though of a reason this might have happened. 

Earlier I was using the 'lapjv' solver for hungarian matching, but then I found that it is bugged and often causes incorrect matches. This could have happened here. When I discovered this I swapped to using the scipy solver, so if this was the issue it will be fixed now.

You can confirm by running the most recent version, and seeing if the version you were using was using 'lapjv'.

Let me know if this solves it. Would love to be able to close this.

Cheers,
Jono

**Comment by Spritea** [comment] 2021-02-10 13:26
Yeah, I download the code which causes the bug in about November last year.

It uses lapjv package, instead of the scipy one in the latest version. With your observation, I guess that could be the reason.

I haven't tested it with the latest code, but I will do in the near future. If it has problem, I would let you know.

The reason I use the old version is I'm more familiar with that. But now, we know it's not reliable, so I would turn to the latest version.

I'd like to close the issue, and thanks for your quick response!

**Closed** 2021-02-10 13:26 UTC
